
server:
  port: 8700

logging:
  level:
    org.springframework.web: TRACE
spring:
  application:
    name: boot-admin
  data:
    jdbc:
      repositories:
        enabled: false
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        health-check-path: /
        health-check-interval: 5s
#debug: true

